{{- if .Values.debug }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate
webhooks:
  - clientConfig:
      url: {{ .Values.ngrok }}
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: ns.{{ .Values.name }}.{{ .Values.namespace}}.svc
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
    sideEffects: None
    timeoutSeconds: 30
    admissionReviewVersions:
      - v1
      - v1alpha1
    namespaceSelector:
      matchExpressions:
        - key: yusur.tech/dpu-auto-injection
          operator: In
          values:
            - enabled
        - key: yusur.tech/dpu-auto-injection
          operator: NotIn
          values:
            - disabled
  - clientConfig:
      url: {{ .Values.ngrok }}
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: object.{{ .Values.name }}.{{ .Values.namespace}}.svc
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
    sideEffects: None
    timeoutSeconds: 30
    admissionReviewVersions:
      - v1
      - v1alpha1
    objectSelector:
      matchExpressions:
        - key: yusur.tech/dpu-injection
          operator: In
          values:
            - "true"
        - key: yusur.tech/dpu-injection
          operator: NotIn
          values:
            - "false"
    namespaceSelector:
      matchExpressions:
        - key: yusur.tech/dpu-auto-injection
          operator: NotIn
          values:
            - enabled
{{- end }}
