apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}
webhooks:
  - name: {{ .Values.name }}.{{ .Values.namespace}}.svc
    clientConfig:
      service:
        name: {{ .Values.name }}
        namespace: {{ .Values.namespace }}
        path: "/mutate"
      caBundle: {{ .Files.Get "./templates/ca.crt" | b64enc }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    timeoutSeconds: 5
    sideEffects: None
    admissionReviewVersions:
      - v1
      - v1alpha1

